use fitness_tracker;

CREATE TABLE app_user (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DOB DATE,
    GENDER VARCHAR(50),
    CURRENT_WEIGHT VARCHAR(50),
    TARGET_WEIGHT VARCHAR(50),
    HEIGHT VARCHAR(50),
    GOAL VARCHAR(50),
    FITNESS_LEVEL VARCHAR(100),
    FOCUS_PART VARCHAR(100),
    DELETED VARCHAR(10),
    CREATED_BY VARCHAR(255),
    CREATED_ON DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    UPDATED_ON DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE exercise (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    BODY_PART VARCHAR(100)
);

CREATE TABLE meal_item (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    CALORIES INT NOT NULL,
    PROTEIN DOUBLE NOT NULL,
    CARBS DOUBLE NOT NULL,
    FATS DOUBLE NOT NULL
);
